### ISSUE TITLE
In cases where IDs have previously been registered under other entities, the MUTATED_EXISTING_ERROR types are not thrown

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/argo-clinical#112]
Steps to reproduce:
1. Commit a succesful registration in QA.
2. Select 1 of the entries that have been committed, and change the data in the file so that the specimen id points to a different donor, and the specimen type is mutated. 

Expected result:
Both SPECIMEN_BELONGS_TO_OTHER_DONOR & MUTATING_EXISTING_DATA for the SpecimenType field should be thrown.

Actual Result :
Only the SPECIMEN_BELONGS_TO_OTHER_DONOR field is thrown.

**Comment by blabadi** [comment]
this logic is in `validation.ts` https://github.com/icgc-argo/argo-clinical/blob/master/src/submission/validation.ts#L336-L381

the fix is to do a db query by the specimenSubmitterId  in that specific program and check if there is any mutation on the attributes (specimenType, tumourNormalDesignation)

same thing can happen to an existing sample if it is attached to a new specimen and in the same time the data was mutated

**Comment by rosibaj** [comment]
verified in postman that all errors ar showing
