### ISSUE TITLE
Feature Request Reuse submitter_follow_up_id, submitter_primary_diagnosis_id, submitter_treatment_id for different submitter_donor_ids

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#555]
Is it possible to allow a `submitter_follow_up_id` to be re-used for a different `submitter_donor_id` (ie. make it a multi-field primary key)? The current validation does not allow it, but it may make more sense from a data submitter's point of view. Would there be any unintended consequences of this (ie. edge cases) that might cause issues if we did it this way?

Example:
![reuse_followup_ids](https://user-images.githubusercontent.com/4992044/83785129-de018680-a65e-11ea-983d-548542781f8b.png)

**Comment by blabadi** [comment]
I don't understand what is the business use case, I'd prefer if you lay out the problem and then we can think of the best way to implement it together, because the answer to what I read above would be no it's not possible because by definition an id defines a single record.

 what this request implies is a design issue in the files them selves and how they are structured

**Comment by rosibaj** [comment]
@blabadi I asked hardeep to create a ticket with her questions so that we would not forget and could discuss on a day when we aren't focusing on release.  My plan is to go in and add more description and discuss, as we usually do before any changes are made, at a later date before we make any changes.

**Comment by blabadi** [comment]
@rosibaj yeah no worries we are not making decisions now

**Comment by hknahal** [comment]
@blabadi No problem, if the  current setup is better, then we'll stick to it. I just wanted to get your thoughts on this. I realize the ticket is not clear and I should have added some actual use cases, but we can discuss it more later.

**Comment by blabadi** [comment]
another thing we can think of is how this compares to other submitter ID like specimen and sample we have always treated them in a certain way, 

also it may be good to also ask the submitters if these ids will be generated by their clinical systems or manually entered that can be a decisive factor

again just things to think about, I'm not closing the door if this is really what we need

**Comment by rosibaj** [comment]
@hknahal is this still a thought/request that we would like to consider?

**Comment by hknahal** [comment]
@rosi No, we can close this ticket.
