### ISSUE TITLE
Dev tools: pre push hook issue🐛 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/argo-clinical#607]
## Describe the bug
 FYI the pre-push hook doesn't work on my mac because grep on mac isn't the gnu version...
So on my machine, I had to do `brew install grep`, then change the hook to the following for it to work:

`git branch | ggrep \"*\" | ggrep -E -v \"^* develop$\" && git branch | ggrep \"*\" | ggrep -E -v \"^* master$\"`

Not sure if anyone else working on this repo has this problem, so I didn't look into a long-term solution, but reporting so you're aware...

It looks like the script is trying to protect develop and `master, which is probably better done through github protected branch...

**Comment by hlminh2000** [comment]
thanks for the ticket @blabadi!

@jaserud I see you added this hook, can you leave a short background on the purpose please? :)

**Comment by jaserud** [comment]
At the time this was really meant as a safety net for me to keep from accidentally pushing to develop or master. Removing this in https://github.com/icgc-argo/argo-clinical/pull/609 since it only works if specific grep is available. Dev tools are meant to help not cause more headaches :stuck_out_tongue: . I think the github control is better to control accidental pushes to dev or master so lets stick with that.

**Comment by rosibaj** [comment]
@jaserud @blabadi this looks mered etc and we have released since then.  i thinkg good to close can someone confirm?

**Comment by blabadi** [comment]
> @jaserud @blabadi this looks mered etc and we have released since then. i thinkg good to close can someone confirm?

yes can be closed
