### ISSUE TITLE
Investigate Clinical Data Aggregation: Charts

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#628]
Currently the date that clinical data is completed is not recorded. 
- Record the date the clinical data was `first noted as completed` 
- If a donor has reached this state, then they contrbute to this data point

**Comment by samrichca** [comment]
changes needed, by repo:

1. argo-clinical
  1. calculate total clinical data completion, which is currently handled in donor-submission-aggregator
  2. add completion date field
  3. remove granular clinical completion
2. donor-submission-aggregator
  1.  remove calculation of clinical data completion percentage, since it's being handled upstream in argo-clinical now
  2. serve clinical completion percentage & date to gateway-api
3. platform-api
  1. clinical completion percentage: no changes needed
  2. clinical completion date: change createdAt to the new field, where indicated in comments
4. gateway-ui
  1. for the clinical chart, request the new field instead of createdAt, where indicated in comments

increasing points estimate to 5
