### ISSUE TITLE
🐛 Missing sample_registration table for LUCA-KR and mismatched record count.

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/argo-clinical#973]
## Describe the bug
The Sample Registration table is missing in the Submitted Data view for the LUCA-KR program, even though it was submitted. The number of records reported (1,422 donors) is different from the Program Dashboard count (1,571 donors)

## Steps To Reproduce
- Go to `Submitted Data` view in LUCA-KR program: https://platform.icgc-argo.org/submission/program/LUCA-KR/clinical-data?donorId=&tab=donor
- The `Sample Registration` link is greyed out (cannot access it)
- The number of records (1,422) is different than the number of donors reported in the Program Dasboard (1,571). This could be related to the 152 donors that were deleted from clinical in this ticket: https://github.com/icgc-argo/workflow-roadmap/issues/267#issuecomment-1536530513 But this would result in 1,419 donors (not 1,422 donors).

![missing_sample_reg](https://github.com/icgc-argo/argo-clinical/assets/4992044/ba905104-be74-43e0-a9b9-d8ddf940d82d)

## Expected behaviour
Expecting to see `Sample Registration` view and updated record count.

**Comment by joneubank** [comment]
Table is failing to load pages due to errors in the requests being sent to clinical API. We are using the full list of donor IDs as a filter on each request and these are being passed as query parameters. The error appears to be from URI being too long for an http request. We will need to refactor the API to move large filters to the body of the request. Will also review at same time the need to filter by ID instead of a more flexible query (like whole study).

**Comment by Buwujiu** [comment]
Jon and Dan are working on a quick fix on UI to not send broken UI on start up, can still break if enter too many donor ids. 
A proper solution in progress.

**Comment by demariadaniel** [comment]
UI fix here: https://github.com/icgc-argo/platform-ui/pull/2662
There are necessary updates to Gateway + Clinical Service to prevent this from happening at all
UI fix is sufficient to prevent it happening on Platform UI in the short term

**Comment by Buwujiu** [comment]
Issue is fixed in prod, closing!
